services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: liga_jovem
      POSTGRES_PASSWORD: liga_jovem
      POSTGRES_DB: liga_jovem
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
